"""
A simple problem to test the scalability of propagators for the cumulative constraint for large sets of tasks with large durations.
Some data files have been randomly generated by Pierre Schaus and used in the conference paper published at CP2015.

The model, below, is close to (can be seen as the close translation of) the one submitted to the 2015/2018 Minizinc challenges.
The MZN model was proposed by the BeCool team at UCLouvain.
No Licence was explicitly mentioned (MIT Licence is assumed).

## Data Example
  0100-4.json

## Model
  constraints: Cumulative, Maximum

## Execution
  python LargeCumulative.py -data=<datafile.json>
  python LargeCumulative.py -data=<datafile.dzn> -parser=LargeCumulative_ParserZ.py

## Links
  - https://link.springer.com/chapter/10.1007/978-3-319-23219-5_11
  - https://www.minizinc.org/challenge2018/results2018.html

## Tags
  crafted, mzn15, mzn18
"""

from pycsp3 import *

limit, durations, heights = data
nTasks = len(durations)

horizon = sum(durations) + 1  # trivial upper bound on the horizon

# x[i] is the starting time of the ith task
x = VarArray(size=nTasks, dom=range(horizon))

# z is the make-span
z = Var(dom=range(horizon))

satisfy(
    # resource cumulative constraint
    Cumulative(origins=x, lengths=durations, heights=heights) <= limit,

    # computing the make-span
    z == Maximum(x[i] + durations[i] for i in range(nTasks)),

    # tag(redundant-constraint)
    [x[i] + durations[i] <= z for i in range(nTasks)]
)

minimize(
    z
)
